Repository AY1920S1-CS2103T-T10-4/main, pull requests merged in 2019-11, with the labels that each got.

#190 Update Ug minor tweaks
  docs/UserGuide.adoc
Labels: type.Chore

#193 Ui bug fix
  src/main/java/seedu/address/ui/PersonDetailCard.java
  src/main/java/seedu/address/ui/util/ScheduleDisplayCard.java
  src/main/resources/view/Calendar.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DefaultStartView.fxml
  src/main/resources/view/GroupListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ScheduleView.fxml
  src/main/resources/view/TabPanel.fxml
  src/main/resources/view/UpcomingScheduleList.fxml
Labels: priority.Medium

#216 LoadModuleList on init
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/nusmods/addmod1.PNG
  docs/images/nusmods/addmod2.PNG
  docs/images/nusmods/addmods1.PNG
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: priority.High

#205 Add initial lesson type and number parameter suggestions for addmod command
  src/main/java/seedu/address/logic/commands/suggestions/AddNusModCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/NusModSuggester.java
Labels: priority.High, severity.Medium, status.Ongoing, type.Enhancement

#235 Fix tag suggestion for editperson and edituser commands
  src/main/java/seedu/address/logic/commands/suggestions/EditPersonCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/EditUserCommandSuggester.java
  src/test/java/seedu/address/logic/commands/suggestions/EditPersonCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/EditUserCommandSuggesterTest.java
Labels: severity.Medium, type.Bug

#239 Suggestions code improvements
  src/main/java/seedu/address/logic/commands/suggestions/DeleteEventCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/DeleteFromGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/EditGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/EditPersonCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/EditUserCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/Suggester.java
  src/test/java/seedu/address/logic/commands/suggestions/AddToGroupCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/DeleteEventCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/DeleteFromGroupCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/DeleteGroupCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/DeletePersonCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/EditCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/EditGroupCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/EditPersonCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/EditUserCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/SuggesterImplTester.java
  src/test/java/seedu/address/logic/commands/suggestions/SuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/SuggestionLogicManagerTest.java
  src/test/java/seedu/address/logic/parser/SuggestingCommandUtilTest.java
Labels: severity.Low, type.Bug

#240 Valid location suggestor
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/suggestions/AddEventCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/Suggester.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/GmapsModelManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/suggestions/AddEventCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/SuggesterTest.java
  src/test/java/seedu/address/model/GmapsModelManagerTest.java
Labels: priority.Medium, type.Enhancement

#243 Fix issue where UiUtilTest may fail as JavaFX is already initialized
  src/test/java/seedu/address/ui/UiUtilTest.java
Labels: priority.High, severity.High, type.Bug

#238 Update Help Window URL and Escape Key to Close
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: severity.High, type.Bug, type.Enhancement

#246 Refactoring and add multiplePrefix checks
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/AddNusModCommandParser.java
  src/main/java/seedu/address/logic/parser/AddNusModsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ClosestLocationCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteFromGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditUserCommandParser.java
  src/main/java/seedu/address/logic/parser/FindGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/PopupCommandParser.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowNusModCommandParser.java
Labels: type.Bug

#242 Clean up code for maps
  src/main/java/seedu/address/logic/commands/PopupCommand.java
  src/main/java/seedu/address/logic/internal/gmaps/ClosestLocation.java
  src/main/java/seedu/address/logic/internal/gmaps/GenerateImage.java
  src/main/java/seedu/address/logic/internal/gmaps/ProcessLocationGraph.java
  src/main/java/seedu/address/model/GmapsModelManager.java
  src/main/java/seedu/address/model/gmaps/Location.java
  src/main/java/seedu/address/websocket/Cache.java
  src/main/java/seedu/address/websocket/GmapsApi.java
  src/main/java/seedu/address/websocket/util/UrlUtil.java
  src/test/data/ApiStubsTest/GmapsDistanceMatrixNOTOK.json
  src/test/java/seedu/address/commons/util/ArrayListUtilTest.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/commons/util/LocationArrayListUtilsTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/ClosestLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/PopupCommandTest.java
  src/test/java/seedu/address/logic/internal/gmaps/ClosestLocationTest.java
  src/test/java/seedu/address/logic/internal/gmaps/GenerateImageTest.java
  src/test/java/seedu/address/logic/internal/gmaps/GmapsJsonUtilsTest.java
  src/test/java/seedu/address/logic/internal/gmaps/ProcessVenuesTest.java
  src/test/java/seedu/address/logic/parser/PopupCommandParserTest.java
  src/test/java/seedu/address/model/GmapsModelManagerTest.java
  src/test/java/seedu/address/model/display/detailwindow/ClosestCommonLocationDataTest.java
  src/test/java/seedu/address/stubs/GmapsApiStub.java
  src/test/java/seedu/address/stubs/SanitizeLocationStub.java
  src/test/java/seedu/address/websocket/CacheTest.java
  src/test/java/seedu/address/websocket/GmapsApiTest.java
Labels: type.Chore

#252 Update UG to resolve PED issues and change Gmaps UG
  docs/UserGuide.adoc
  docs/images/gmaps/SuccessfulPopup.png
  docs/images/gmaps/UnsuccessfulPopup.png
Labels: type.Chore

#255 Prioritize exact prefix match for command suggestions
  src/main/java/seedu/address/logic/commands/suggestions/SuggestionLogicManager.java
Labels: type.Enhancement

#261 Storage test
  src/main/java/seedu/address/model/TimeBook.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupList.java
  src/main/java/seedu/address/model/mapping/PersonToGroupMapping.java
  src/main/java/seedu/address/model/mapping/PersonToGroupMappingList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/main/java/seedu/address/storage/JsonSerializableTimeBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableTimeBookTest/duplicatePersonTimeBook.json
  src/test/data/JsonSerializableTimeBookTest/invalidTimeBook.json
  src/test/data/JsonSerializableTimeBookTest/typicalTimeBook.json
  src/test/data/JsonTimeBookStorageTest/invalidAndValidPersonTimeBook.json
  src/test/data/JsonTimeBookStorageTest/invalidPersonTimeBook.json
  src/test/data/JsonTimeBookStorageTest/notJsonFormatTimeBook.json
  src/test/data/JsonTimeBookStorageTest/typicalTimeBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializableTimeBookTest.java
  src/test/java/seedu/address/storage/JsonTimeBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTimeBook.java
  src/test/java/seedu/address/testutil/personutil/TypicalPersonDescriptor.java
Labels: type.Chore

#275 Documentation changes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/command-suggestions/DeletePersonSequenceDiagram.svg
  docs/images/command-suggestions/FindPersonSequenceDiagram.svg
  docs/images/command-suggestions/FullSequenceDiagram.svg
  docs/images/command-suggestions/Step1.svg
  docs/images/command-suggestions/Step2.svg
  docs/images/command-suggestions/Step3.svg
  docs/images/command-suggestions/Step4.svg
  docs/images/command-suggestions/Step5.svg
  docs/images/command-suggestions/Step6.svg
  docs/images/command-suggestions/Step7.svg
  docs/images/command-suggestions/SuggestingCommands.svg
  docs/images/command-suggestions/developer-guide-caret-within-arguments.png
  docs/images/command-suggestions/developer-guide-caret-within-commandWord.png
  docs/images/command-suggestions/project-portfolio-commands.png
  docs/images/command-suggestions/project-portfolio-deletefromgroup.png
  docs/team/aidilfbk.adoc
Labels: type.Chore
