Repository AY1920S1-CS2103T-T10-4/main, pull requests merged in 2019-10, with the labels that each got.

#89 Update ug
  docs/UserGuide.adoc
Labels: severity.Low, type.Enhancement

#100 Gmaps test2
  src/main/java/seedu/address/commons/exceptions/TimeBookInvalidLocation.java
  src/main/java/seedu/address/commons/exceptions/TimeBookInvalidState.java
  src/main/java/seedu/address/logic/commands/ClosestLocationCommand.java
  src/main/java/seedu/address/logic/internal/gmaps/LocationArrayListUtils.java
  src/main/java/seedu/address/logic/internal/gmaps/ProcessLocationGraph.java
  src/main/java/seedu/address/logic/internal/gmaps/ProcessVenues.java
  src/main/java/seedu/address/logic/internal/gmaps/SanitizeLocation.java
  src/main/java/seedu/address/logic/internal/gmaps/UpdateGmapsSerialization.java
  src/main/java/seedu/address/model/gmaps/Location.java
  src/main/java/seedu/address/model/gmaps/LocationGraph.java
  src/main/java/seedu/address/websocket/GmapsApi.java
  src/test/data/ApiStubsTest/GmapsPlacesOK.json
  src/test/data/ApiStubsTest/GmapsPlacesZERO_RESULTS.json
  src/test/java/seedu/address/logic/internal/gmaps/LocationArrayListUtilsTest.java
  src/test/java/seedu/address/logic/internal/gmaps/ProcessVenuesTest.java
  src/test/java/seedu/address/model/gmaps/LocationGraphTest.java
  src/test/java/seedu/address/stubs/GmapsApiStub.java
  src/test/java/seedu/address/stubs/LocationGraphStub.java
  src/test/java/seedu/address/stubs/ProcessVenuesStub.java
  src/test/java/seedu/address/stubs/SanitizeLocationStub.java
Labels: severity.Medium, type.Enhancement

#101 Implement addnusmods/addnusmod command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/AppSettings.java
  src/main/java/seedu/address/commons/util/SimpleJsonUtil.java
  src/main/java/seedu/address/logic/commands/AddNusModCommand.java
  src/main/java/seedu/address/logic/commands/AddNusModsCommand.java
  src/main/java/seedu/address/logic/commands/ShowNusModCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/ModuleToEventMappingException.java
  src/main/java/seedu/address/logic/internal/gmaps/ProcessVenues.java
  src/main/java/seedu/address/logic/parser/AddNusModCommandParser.java
  src/main/java/seedu/address/logic/parser/AddNusModsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SuggestingCommandUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/NusModsData.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/module/LessonNo.java
  src/main/java/seedu/address/model/module/NusModsShareLink.java
  src/main/java/seedu/address/websocket/ApiCache.java
  src/main/java/seedu/address/websocket/NusModsApi.java
  src/main/java/seedu/address/websocket/NusModsParser.java
Labels: severity.High, type.Story

#103 Gmaps integrate w back end
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/VenueUtil.java
  src/main/java/seedu/address/logic/commands/ClosestLocationCommand.java
  src/main/java/seedu/address/logic/internal/gmaps/ClosestLocation.java
  src/main/java/seedu/address/logic/parser/SuggestingCommandUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/commons/util/VenueUtilTest.java
  src/test/java/seedu/address/logic/internal/gmaps/ClosestLocationTest.java
  src/test/java/seedu/address/logic/internal/gmaps/SanitizeLocationTest.java
Labels: priority.Medium, status.Ongoing

#109 Add Command History
  src/main/java/seedu/address/logic/commands/CommandHistory.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/SuggestingCommandBox.java
  src/main/java/seedu/address/ui/UiUtil.java
Labels: priority.Medium, type.Enhancement

#107 Implemented free time schedule
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/AddNusModCommand.java
  src/main/java/seedu/address/logic/commands/AddNusModsCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddToGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditGroupCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/AddToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/display/detailwindow/DayTimeslot.java
  src/main/java/seedu/address/model/display/detailwindow/DetailWindowDisplay.java
  src/main/java/seedu/address/model/display/detailwindow/FreeSchedule.java
  src/main/java/seedu/address/model/display/detailwindow/FreeTimeslot.java
  src/main/java/seedu/address/model/display/detailwindow/WeekSchedule.java
  src/main/java/seedu/address/model/display/sidepanel/GroupDisplay.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupDescription.java
  src/main/java/seedu/address/model/group/GroupDescriptor.java
  src/main/java/seedu/address/model/group/GroupList.java
  src/main/java/seedu/address/model/mapping/PersonToGroupMapping.java
  src/main/java/seedu/address/model/mapping/PersonToGroupMappingList.java
  src/main/java/seedu/address/model/mapping/Role.java
  src/main/java/seedu/address/model/person/ScheduleStub.java
  src/main/java/seedu/address/model/person/schedule/Event.java
  src/main/java/seedu/address/model/person/schedule/Schedule.java
  src/main/java/seedu/address/model/person/schedule/Timeslot.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedMapping.java
  src/main/java/seedu/address/ui/GroupCard.java
  src/main/java/seedu/address/ui/GroupDetailsView.java
  src/main/java/seedu/address/ui/PersonDetailsView.java
  src/main/java/seedu/address/ui/util/GroupDetailCard.java
  src/main/java/seedu/address/ui/util/GroupDetailsExport.java
  src/main/java/seedu/address/ui/util/MemberList.java
  src/main/resources/view/GroupListCard.fxml
  src/test/java/seedu/address/logic/commands/AddToGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddToGroupCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/grouputil/TypicalGroups.java
Labels: priority.High, type.Chore

#105 Implement API Caching
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/SimpleJsonUtil.java
  src/main/java/seedu/address/logic/commands/AddNusModCommand.java
  src/main/java/seedu/address/logic/commands/AddNusModsCommand.java
  src/main/java/seedu/address/logic/commands/ShowNusModCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/NusModsData.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCondensed.java
  src/main/java/seedu/address/model/module/ModuleCondensedList.java
  src/main/java/seedu/address/model/module/ModuleId.java
  src/main/java/seedu/address/model/module/ModuleList.java
  src/main/java/seedu/address/websocket/Cache.java
  src/main/java/seedu/address/websocket/CacheFileNames.java
  src/main/java/seedu/address/websocket/NusModsParser.java
Labels: priority.Medium, type.Enhancement

#119 Enhancement integrate Gmaps to Api Caching
  src/main/java/seedu/address/logic/internal/gmaps/ProcessVenues.java
  src/main/java/seedu/address/logic/internal/gmaps/UpdateGmapsSerialization.java
  src/main/java/seedu/address/model/gmaps/Location.java
  src/main/java/seedu/address/websocket/Cache.java
  src/main/java/seedu/address/websocket/CacheFileNames.java
  src/main/java/seedu/address/websocket/GmapsApi.java
  src/main/java/seedu/address/websocket/util/ApiQuery.java
  src/main/java/seedu/address/websocket/util/ApiQueryFactory.java
  src/main/java/seedu/address/websocket/util/CacheApiQuery.java
  src/main/java/seedu/address/websocket/util/UrlUtil.java
  src/main/resources/ApiResponseCache/GoogleMapsApi/DistanceMatrix.json
  src/main/resources/ApiResponseCache/GoogleMapsApi/Places.json
  src/main/resources/ApiResponseCache/GoogleMapsApi/test.json
  src/test/java/seedu/address/model/gmaps/LocationGraphTest.java
  src/test/java/seedu/address/model/gmaps/LocationTest.java
  src/test/java/seedu/address/stubs/ProcessVenuesStub.java
  src/test/java/seedu/address/websocket/CacheTest.java
  src/test/java/seedu/address/websocket/util/UrlUtilTest.java
  src/test/resources/ApiResponseCache/GoogleMapsApi/PlacesTest.json
Labels: priority.Medium, severity.Low, status.Ongoing

#130 Dg gmaps wk9
  docs/DeveloperGuide.adoc
  docs/images/gmaps/ApiDiagram.png
  docs/images/gmaps/ClosestLocationSequenceDiagram.png
  docs/images/gmaps/GmapsArchitectureDiagram.png
  docs/images/gmaps/MatrixCreationSequenceDiagram.png
Labels: priority.High, severity.Medium, type.Enhancement

#126 Add command and argument sensitive suggestions
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/suggestions/AddEventCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/AddGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/AddNusModsCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/AddPersonCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/AddToGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/DeleteGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/DeletePersonCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/EditGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/EditPersonCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/FindPersonCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/NusModSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/ShowNusModCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/Suggester.java
  src/main/java/seedu/address/logic/commands/suggestions/SuggestionLogicManager.java
  src/main/java/seedu/address/logic/commands/suggestions/stateless/GroupNameSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/stateless/NullSuggester.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentList.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CommandArgument.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SuggestingCommandBox.java
Labels: priority.Medium, status.Ongoing, type.Enhancement

#133 Update version number
  src/main/java/seedu/address/MainApp.java
Labels: priority.Low

#140 Update the Gmaps UG
  docs/UserGuide.adoc
  docs/images/FreeTimePopup.png
Labels: priority.Low, type.Chore

#138 Update User Guide
  docs/UserGuide.adoc
Labels: severity.Low, type.Chore

#145 Add sample data
  src/main/resources/timebook-sample-data.json
Labels: priority.Medium, type.Chore

#146 Add Suggester for show command
  src/main/java/seedu/address/logic/commands/suggestions/ShowCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/Suggester.java
Labels: priority.Medium, severity.Low, type.Enhancement

#150 Improve code quality and coverage
  build.gradle
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/commands/CommandHistory.java
  src/main/java/seedu/address/logic/commands/suggestions/AddEventCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/AddGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/AddNusModsCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/AddPersonCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/AddToGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/DeleteGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/DeletePersonCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/EditGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/EditPersonCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/FindPersonCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/ShowNusModCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/Suggester.java
  src/main/java/seedu/address/logic/commands/suggestions/SuggestionLogicManager.java
  src/main/java/seedu/address/logic/commands/suggestions/stateless/GroupNameSuggester.java
  src/main/java/seedu/address/logic/parser/CommandArgument.java
  src/main/java/seedu/address/ui/SuggestingCommandBox.java
  src/test/java/seedu/address/commons/util/CollectionUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandHistoryTest.java
  src/test/java/seedu/address/logic/commands/suggestions/AddEventCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/AddGroupCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/AddNusModsCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/AddPersonCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/AddToGroupCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/DeleteGroupCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/DeletePersonCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/EditCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/EditGroupCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/EditPersonCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/FindPersonCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/GroupNameSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/ShowCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/SuggesterImplTester.java
  src/test/java/seedu/address/logic/commands/suggestions/SuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/SuggestionLogicManagerTest.java
  src/test/java/seedu/address/logic/parser/CommandArgumentTest.java
Labels: type.Chore

#154 Resolve NPE for Gmaps
  src/main/java/seedu/address/logic/internal/gmaps/ClosestLocation.java
Labels: type.Chore

#156 Gmaps closest location bug to integrate with front end
  src/main/java/seedu/address/logic/internal/gmaps/ClosestLocation.java
  src/main/java/seedu/address/logic/internal/gmaps/ProcessLocationGraph.java
  src/main/java/seedu/address/websocket/Cache.java
  src/main/resources/ApiResponseCache/GoogleMapsApi/DistanceMatrix.json
  src/main/resources/ApiResponseCache/GoogleMapsApi/Places.json
  src/main/resources/ApiResponseCache/NusModsApi/modules.json
  src/test/java/seedu/address/logic/internal/gmaps/ClosestLocationTest.java
  src/test/java/seedu/address/websocket/CacheTest.java
Labels: severity.High, type.Chore

#157 Integration with Gmaps
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/display/DisplayModelManager.java
  src/main/java/seedu/address/model/display/detailwindow/DetailWindowDisplay.java
  src/main/java/seedu/address/model/display/detailwindow/FreeTimeslot.java
  src/main/java/seedu/address/model/util/SampleEvents.java
  src/main/java/seedu/address/model/util/SamplePersonList.java
Labels: priority.High, type.Enhancement

#165 Add dynamic resizing of suggestions picker UI element
  src/main/java/seedu/address/ui/SuggestingCommandBox.java
Labels: severity.Medium, type.Bug

#166 Regroup commands in User Guide
  docs/UserGuide.adoc
Labels: priority.High, type.Chore

#162 Implemented delete event command and freetimeslot ID
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddNusModCommand.java
  src/main/java/seedu/address/logic/commands/AddNusModsCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/TimeBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/display/schedulewindow/FreeTimeslot.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonList.java
  src/main/java/seedu/address/model/person/ScheduleStub.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/person/exceptions/EventNotFoundException.java
  src/main/java/seedu/address/model/person/schedule/Schedule.java
  src/main/java/seedu/address/model/util/SamplePersonList.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/schedule/ScheduleTest.java
  src/test/java/seedu/address/testutil/scheduleutil/TypicalSchedule.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#167 Ug wk 11 for popup
  README.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelClassDiagram.puml
  docs/images/Ui.png
  docs/images/gmaps/SuccessfulPopup.png
  docs/images/gmaps/UnsuccessfulPopup.png
Labels: priority.Low, type.Chore

#169 Add command suggestions to user guide
  docs/UserGuide.adoc
  docs/images/command-suggestions/user-guide-example-step1.png
  docs/images/command-suggestions/user-guide-example-step2.png
  docs/images/command-suggestions/user-guide-example-step3.png
  docs/images/command-suggestions/user-guide-example-step4.png
  docs/images/command-suggestions/user-guide-example-step5.png
  docs/images/command-suggestions/user-guide-example-step6.png
  docs/images/command-suggestions/user-guide-example-step7.png
  docs/images/command-suggestions/user-guide-example-step8.png
Labels: type.Chore

#172 UG Updates
  docs/UserGuide.adoc
  docs/images/nusmods/addmod1.PNG
  docs/images/nusmods/addmod2.PNG
  docs/images/nusmods/addmods1.PNG
  docs/images/nusmods/addmods2.PNG
Labels: type.Chore

#180 Fix bug in suggestions and update command parameters
  src/main/java/seedu/address/logic/commands/suggestions/DeleteFromGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/EditGroupCommandSuggester.java
  src/main/java/seedu/address/logic/commands/suggestions/Suggester.java
  src/main/java/seedu/address/logic/commands/suggestions/SuggestionLogicManager.java
  src/main/java/seedu/address/logic/parser/SuggestingCommandUtil.java
  src/test/java/seedu/address/logic/commands/suggestions/DeleteFromGroupCommandSuggesterTest.java
  src/test/java/seedu/address/logic/commands/suggestions/EditGroupCommandSuggesterTest.java
Labels: severity.Medium, type.Bug

#183 Gmaps error handling
  src/main/java/seedu/address/commons/util/ArrayListUtil.java
  src/main/java/seedu/address/logic/commands/PopupCommand.java
  src/main/java/seedu/address/logic/internal/gmaps/ClosestLocation.java
  src/main/java/seedu/address/model/display/detailwindow/ClosestCommonLocationData.java
  src/test/java/seedu/address/logic/commands/ClosestLocationCommandTest.java
  src/test/java/seedu/address/logic/internal/gmaps/ClosestLocationTest.java
  src/test/java/seedu/address/model/GmapsModelManagerTest.java
  src/test/java/seedu/address/model/display/detailwindow/ClosestCommonLocationDataTest.java
Labels: type.Chore

#177 Updated Userguide
  docs/UserGuide.adoc
Labels: priority.Medium, severity.Medium, type.Chore
